### ISSUE TITLE
Can't verify signed message 

### ISSUE THREAD

**Issue by swdee** [superdarkbit/nano-bip32-ed25519#1]
Using the python implementation I try to sign a message from a derived key but when verifying it returns false.

Using the following code;
```
from bip32_ed25519 import *

# get HD node using secret
secret = str.encode("8f434346648f6b96df89dda901c5176b")
node = derive_chain(secret, "44'/165'" )

# generate private key
chKeys, chA, chC = private_child_key(node, 0)
print("chKeys=", chKeys[0].hex(), " ", chKeys[1].hex() )
print("chA=", chA.hex() )
print("chC=", chC.hex() )

# sign
msg = str.encode("hello")
sig = special_signing(chKeys[0], chKeys[1], chA, msg )
print("sig=", sig.hex() )


# verify
res = verify(chA, msg, sig)
print("res=", res)
```

This outputs the following;
```
chKeys= 385cc8536edbb90d4e70368ecff4f280187658fa6a07a4334827a95f9543264d   fe2d23dd11b1bda3541707262787567f1c0edda1a2d545043530d9ebd974cf00
chA= 37962ee48657afac972e3ebd71c0d4e41206d0c6dd6cbf92aef73d866b118a85
chC= 4d38e9608c63fd4db543619050ff67a883d08d54cc3938741a744c23b85d8305
sig= 4cd4d179f7fbcdc8e62755f15f665ac4eca74f2db55967b74fbb60880ae55c6fe9e1eeae1a0d0dba5b741da05052472055e252f7bacb17467810da340cdb100f
res= False
```

The expected output would be `res= True` at the end.

Would you clarify if this implementation is working?

**Comment by superdarkbit** [comment]
Hi @swdee,

The implementation is not working. I shouldn't have included it and I'm going to remove it. As I said in the [README.md](https://github.com/superdarkbit/nano-bip32-ed25519/blob/master/python_equivalents/README.md): 

> To verify message signatures created using the code found here, utilize the python-pure25519-blake library or any other library that can verify BLAKE2b hash function based Ed25519 signatures.
> 
> For the python-pure25519-blake library, install using the commands "python setup.py build" and "python setup.py install". To verify messages, create a verifying key object using "ed25519_oop.VerifyingKey" and then check for if the verify function returns None. If it returns None, then the signature is valid.

Upon reflection, I should really just incorporate that VerifyingKey method inside of this library itself and not expect anyone to do this extra task, so this is mea culpa.

Sorry for the late response and hope I didn't waste any time you could have spent testing this library out.

Btw, using ed25519_oop.VerifyingKey with your code and inputs, the signature is verified.

**Comment by swdee** [comment]
Thanks for the direction I can get it to verify using the pure25519 library.  For reference a complete solution here;

```
from bip32_ed25519 import *
from pure25519 import ed25519_oop

# get HD node using secret
secret = str.encode("8f434346648f6b96df89dda901c5176b")
node = derive_chain(secret, "44'/165'" )

# generate private key
chKeys, chA, chC = private_child_key(node, 0)
print("chKeys=", chKeys[0].hex(), " ", chKeys[1].hex() )
print("chA=", chA.hex() )
print("chC=", chC.hex() )

# sign
msg = str.encode("hello")
sig = special_signing(chKeys[0], chKeys[1], chA, msg )
print("sig=", sig.hex() )

# verify
vk = ed25519_oop.VerifyingKey(chA)
res = vk.verify(sig, msg)

print("res=", res)
```

Another thing is the code jumps between using Affine points with Big Math and Extended points using Scalar Math.  I realised you have used a number of sources to get this working solution, but do you have any plans to refactor the solution to use Extended/Scalar Math exclusively as it is more performant?

**Comment by superdarkbit** [comment]
So I guess you mean like turning this:

`(r + (x * int.from_bytes(kL, 'little'))) % ed25519.l)`

into something where`r`, `x`, and the other components are first transformed into their extended point forms and the expression is evaluated using extended/scalar math.

[This](http://www.hyperelliptic.org/EFD/g1p/auto-twisted-extended-1.html) (http://www.hyperelliptic.org/EFD/g1p/auto-twisted-extended-1.html) seems to be where algorithms for different extended math operators were obtained for the existing ed25519.py library I used. Do you know where to get code for performing the modulus operator in extended math though? Unless that's a foolish/ridiculous question.

**Comment by swdee** [comment]
Yeah its a bit out of my Math ability, but the Scalar Math implementations are referred to as "Supercop ref10", with some python and JS bindings to the C implementation here;

https://github.com/1p6/supercop.js
https://github.com/warner/python-ed25519

It would depend on ones use case as to if implementing it is worth while though, its probably a premature optimisation, there is also the Radix 51 Asm implementation which is faster again.

**Comment by superdarkbit** [comment]
Maybe if more calls for performance optimization I'll study this more and branch (if no one themselves forks it to make optimizations before then).

I'll also say I like the readability of the code currently in the sense that you can map it to the steps in the algorithms from the "BIP32-Ed25519 Hierarchical Deterministic Keys over a Non-linear Keyspace" paper easily IMO, and making the optimizations may break such readability.

I'll close this for now as I don't want to keep off topic of the original issue.
